;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	coffee-dedent-line-backspace
	kill-region
	))

(setq mc/cmds-to-run-once
      '(
	autopair-insert-or-skip-quote
	js3-mode-show-node
	))
